/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package movierecommender;

/**
 *
 * @author Nour07
 */
public class GUI extends javax.swing.JFrame {
    private MovieRecommendationSystem system;
    /**
     * Creates new form GUI
     */
    public GUI() {
        initComponents();
        try {
            system = new MovieRecommendationSystem("main_data.csv", "movies.csv", "target_user.csv");

            // Clear default NetBeans items just in case
            cmbTargetUser.removeAllItems();

            for (String id : system.getTargetUserIds()) {
                cmbTargetUser.addItem(id);
            }
            
            btnTargetRecommend.setText("GetRecommendations");
            txtX1.setText(""); txtX1.setToolTipText("Enter X (Number of similar users)");
            txtK1.setText(""); txtK1.setToolTipText("Enter K (Movies per user)");
            this.setTitle("Movie Recommender - Target User");
            this.setLocationRelativeTo(null); // Center window
            // -------------------------------

        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error loading files: " + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cmbTargetUser = new javax.swing.JComboBox<>();
        txtX1 = new javax.swing.JTextField();
        txtK1 = new javax.swing.JTextField();
        btnTargetRecommend = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAreaTargetResult = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cmbTargetUser.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cmbTargetUser.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbTargetUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbTargetUserActionPerformed(evt);
            }
        });

        txtX1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        txtK1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        btnTargetRecommend.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnTargetRecommend.setText("jButton1");
        btnTargetRecommend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTargetRecommendActionPerformed(evt);
            }
        });

        txtAreaTargetResult.setColumns(20);
        txtAreaTargetResult.setRows(5);
        jScrollPane1.setViewportView(txtAreaTargetResult);

        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton1.setText("Next Page");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtX1)
                    .addComponent(cmbTargetUser, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtK1)
                    .addComponent(btnTargetRecommend, javax.swing.GroupLayout.DEFAULT_SIZE, 307, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cmbTargetUser, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtX1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtK1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(btnTargetRecommend, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(36, 36, 36)
                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTargetRecommendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTargetRecommendActionPerformed
        // TODO add your handling code here:
        try {
            String targetId = cmbTargetUser.getSelectedItem().toString();
            int x = Integer.parseInt(txtX1.getText());
            int k = Integer.parseInt(txtK1.getText());

            java.util.ArrayList<String> recs = system.recommendForTargetUser(targetId, x, k);

            txtAreaTargetResult.setText("");
            for (String movie : recs) {
                txtAreaTargetResult.append(movie + "\n");
            }
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
        }
    }//GEN-LAST:event_btnTargetRecommendActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        GUI2 g = new GUI2();
        g.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void cmbTargetUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbTargetUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbTargetUserActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnTargetRecommend;
    private javax.swing.JComboBox<String> cmbTargetUser;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtAreaTargetResult;
    private javax.swing.JTextField txtK1;
    private javax.swing.JTextField txtX1;
    // End of variables declaration//GEN-END:variables
}
