/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package movierecommender;

/**
 *
 * @author Nour07
 */
public class GUI2 extends javax.swing.JFrame {

    private MovieRecommendationSystem system;

    /**
     * Creates new form GUI2
     */
    public GUI2() {
        initComponents();
        try {
            system = new MovieRecommendationSystem("main_data.csv", "movies.csv", "target_user.csv");

            java.util.ArrayList<String> randomMovies = system.getRandomMovieNames(10);
            
            // Clear default items generated by NetBeans
            cmbMovie1.removeAllItems(); cmbMovie2.removeAllItems(); cmbMovie3.removeAllItems();
            cmbMovie4.removeAllItems(); cmbMovie5.removeAllItems();

            for (String movie : randomMovies) {
                cmbMovie1.addItem(movie);
                cmbMovie2.addItem(movie);
                cmbMovie3.addItem(movie);
                cmbMovie4.addItem(movie);
                cmbMovie5.addItem(movie);
            }
            
            // --- ADD THESE MISSING PARTS ---
            btnMovieRecommend.setText("Get Recommendations");
            txtRating1.setText(""); txtRating1.setToolTipText("Rating 1-5");
            txtRating2.setText(""); txtRating2.setToolTipText("Rating 1-5");
            txtRating3.setText(""); txtRating3.setToolTipText("Rating 1-5");
            txtRating4.setText(""); txtRating4.setToolTipText("Rating 1-5");
            txtRating5.setText(""); txtRating5.setToolTipText("Rating 1-5");
            
            txtX2.setText(""); txtX2.setToolTipText("Enter X (Users)");
            txtK2.setText(""); txtK2.setToolTipText("Enter K (Movies)");
            
            this.setTitle("Movie Recommender - Manual Ratings");
            this.setLocationRelativeTo(null); // Center window
            // -------------------------------

        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error loading files: " + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cmbMovie1 = new javax.swing.JComboBox<>();
        cmbMovie2 = new javax.swing.JComboBox<>();
        cmbMovie3 = new javax.swing.JComboBox<>();
        cmbMovie4 = new javax.swing.JComboBox<>();
        cmbMovie5 = new javax.swing.JComboBox<>();
        txtRating1 = new javax.swing.JTextField();
        txtRating2 = new javax.swing.JTextField();
        txtRating3 = new javax.swing.JTextField();
        txtRating4 = new javax.swing.JTextField();
        txtRating5 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAreaMovieResult = new javax.swing.JTextArea();
        txtX2 = new javax.swing.JTextField();
        txtK2 = new javax.swing.JTextField();
        btnMovieRecommend = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cmbMovie1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cmbMovie1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Movie A", "Movie B", "Movie C", "Movie D", "Movie E" }));
        cmbMovie1.setPreferredSize(new java.awt.Dimension(150, 50));
        cmbMovie1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbMovie1ActionPerformed(evt);
            }
        });

        cmbMovie2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cmbMovie2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Movie A", "Movie B", "Movie C", "Movie D", "Movie E" }));
        cmbMovie2.setPreferredSize(new java.awt.Dimension(150, 50));
        cmbMovie2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbMovie2ActionPerformed(evt);
            }
        });

        cmbMovie3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cmbMovie3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Movie A", "Movie B", "Movie C", "Movie D", "Movie E" }));
        cmbMovie3.setPreferredSize(new java.awt.Dimension(150, 50));
        cmbMovie3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbMovie3ActionPerformed(evt);
            }
        });

        cmbMovie4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cmbMovie4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Movie A", "Movie B", "Movie C", "Movie D", "Movie E" }));
        cmbMovie4.setPreferredSize(new java.awt.Dimension(150, 50));
        cmbMovie4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbMovie4ActionPerformed(evt);
            }
        });

        cmbMovie5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cmbMovie5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Movie A", "Movie B", "Movie C", "Movie D", "Movie E" }));
        cmbMovie5.setPreferredSize(new java.awt.Dimension(150, 50));
        cmbMovie5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbMovie5ActionPerformed(evt);
            }
        });

        txtRating1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtRating1.setPreferredSize(new java.awt.Dimension(200, 50));

        txtRating2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtRating2.setPreferredSize(new java.awt.Dimension(200, 50));
        txtRating2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRating2ActionPerformed(evt);
            }
        });

        txtRating3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtRating3.setPreferredSize(new java.awt.Dimension(200, 50));

        txtRating4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtRating4.setPreferredSize(new java.awt.Dimension(200, 50));

        txtRating5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtRating5.setPreferredSize(new java.awt.Dimension(200, 50));

        txtAreaMovieResult.setColumns(20);
        txtAreaMovieResult.setRows(5);
        jScrollPane1.setViewportView(txtAreaMovieResult);

        txtX2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtX2.setPreferredSize(new java.awt.Dimension(150, 50));

        txtK2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtK2.setPreferredSize(new java.awt.Dimension(150, 50));

        btnMovieRecommend.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnMovieRecommend.setText("Recommend");
        btnMovieRecommend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMovieRecommendActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cmbMovie1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbMovie2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbMovie3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbMovie4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbMovie5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(txtX2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtK2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtRating5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtRating4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtRating3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtRating2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtRating1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(btnMovieRecommend, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmbMovie1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtRating1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmbMovie2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtRating2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmbMovie3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtRating3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmbMovie4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtRating4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmbMovie5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtRating5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(txtX2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtK2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(btnMovieRecommend, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(44, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtRating2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRating2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRating2ActionPerformed
    private void addMovieRating(java.util.HashMap<Integer, Integer> selectedRatings,
            javax.swing.JComboBox<String> combo,
            javax.swing.JTextField ratingField) {
        String movieName = combo.getSelectedItem().toString();
        int movieId = system.getMovieIdByName(movieName);
        int rating = Integer.parseInt(ratingField.getText());

        if (rating < 1 || rating > 5) {
            throw new IllegalArgumentException("Ratings must be between 1 and 5");
        }

        selectedRatings.put(movieId, rating);
    }
    private void btnMovieRecommendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMovieRecommendActionPerformed
        // TODO add your handling code here:
        try {
            int x = Integer.parseInt(txtX2.getText());
            int k = Integer.parseInt(txtK2.getText());

            java.util.HashMap<Integer, Integer> selectedRatings = new java.util.HashMap<>();

            addMovieRating(selectedRatings, cmbMovie1, txtRating1);
            addMovieRating(selectedRatings, cmbMovie2, txtRating2);
            addMovieRating(selectedRatings, cmbMovie3, txtRating3);
            addMovieRating(selectedRatings, cmbMovie4, txtRating4);
            addMovieRating(selectedRatings, cmbMovie5, txtRating5);

            java.util.ArrayList<String> recs = system.recommendFromManualRatings(selectedRatings, x, k);

            txtAreaMovieResult.setText("");
            for (String movie : recs) {
                txtAreaMovieResult.append(movie + "\n");
            }
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
        }
    }//GEN-LAST:event_btnMovieRecommendActionPerformed

    private void cmbMovie1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbMovie1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbMovie1ActionPerformed

    private void cmbMovie2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbMovie2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbMovie2ActionPerformed

    private void cmbMovie3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbMovie3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbMovie3ActionPerformed

    private void cmbMovie4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbMovie4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbMovie4ActionPerformed

    private void cmbMovie5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbMovie5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbMovie5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMovieRecommend;
    private javax.swing.JComboBox<String> cmbMovie1;
    private javax.swing.JComboBox<String> cmbMovie2;
    private javax.swing.JComboBox<String> cmbMovie3;
    private javax.swing.JComboBox<String> cmbMovie4;
    private javax.swing.JComboBox<String> cmbMovie5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtAreaMovieResult;
    private javax.swing.JTextField txtK2;
    private javax.swing.JTextField txtRating1;
    private javax.swing.JTextField txtRating2;
    private javax.swing.JTextField txtRating3;
    private javax.swing.JTextField txtRating4;
    private javax.swing.JTextField txtRating5;
    private javax.swing.JTextField txtX2;
    // End of variables declaration//GEN-END:variables
}
