/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package movierecommender;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.HashSet;
import javax.swing.*;

/**
 *
 * @author Nour07
 */
public class GUI2 extends javax.swing.JFrame {

    private MovieRecommendationSystem system;
    private GUI previousPage;

    /**
     * Creates new form GUI2
     */
    public GUI2() {
        this(null);
    }
    public GUI2(GUI previousPage) {
        this.previousPage = previousPage;
        initComponents();
        try {
            cmbMovie1.removeAllItems();
            cmbMovie2.removeAllItems();
            cmbMovie3.removeAllItems();
            cmbMovie4.removeAllItems();
            cmbMovie5.removeAllItems();
            this.setLocationRelativeTo(null);
            system = new MovieRecommendationSystem("main_data.csv", "movies.csv", "target_user.csv");

            ArrayList<String> randomMovies = system.getRandomMovieNames(10);

            for (String movie : randomMovies) {
                cmbMovie1.addItem(movie);
                cmbMovie2.addItem(movie);
                cmbMovie3.addItem(movie);
                cmbMovie4.addItem(movie);
                cmbMovie5.addItem(movie);
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error loading files: " + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cmbMovie1 = new javax.swing.JComboBox<>();
        cmbMovie2 = new javax.swing.JComboBox<>();
        cmbMovie3 = new javax.swing.JComboBox<>();
        cmbMovie4 = new javax.swing.JComboBox<>();
        cmbMovie5 = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAreaMovieResult = new javax.swing.JTextArea();
        btnMovieRecommend = new javax.swing.JButton();
        spnRating2 = new javax.swing.JSpinner();
        spnRating3 = new javax.swing.JSpinner();
        spnRating1 = new javax.swing.JSpinner();
        spnRating4 = new javax.swing.JSpinner();
        spnRating5 = new javax.swing.JSpinner();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        spnX2 = new javax.swing.JSpinner();
        spnK2 = new javax.swing.JSpinner();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnPreviousPage = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cmbMovie1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cmbMovie1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Movie A", "Movie B", "Movie C", "Movie D", "Movie E" }));
        cmbMovie1.setPreferredSize(new java.awt.Dimension(300, 45));

        cmbMovie2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cmbMovie2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Movie A", "Movie B", "Movie C", "Movie D", "Movie E" }));
        cmbMovie2.setPreferredSize(new java.awt.Dimension(300, 45));

        cmbMovie3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cmbMovie3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Movie A", "Movie B", "Movie C", "Movie D", "Movie E" }));
        cmbMovie3.setPreferredSize(new java.awt.Dimension(300, 45));

        cmbMovie4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cmbMovie4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Movie A", "Movie B", "Movie C", "Movie D", "Movie E" }));
        cmbMovie4.setPreferredSize(new java.awt.Dimension(300, 45));

        cmbMovie5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cmbMovie5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Movie A", "Movie B", "Movie C", "Movie D", "Movie E" }));
        cmbMovie5.setPreferredSize(new java.awt.Dimension(300, 45));

        txtAreaMovieResult.setColumns(20);
        txtAreaMovieResult.setRows(5);
        jScrollPane1.setViewportView(txtAreaMovieResult);

        btnMovieRecommend.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnMovieRecommend.setText("Recommend");
        btnMovieRecommend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMovieRecommendActionPerformed(evt);
            }
        });

        spnRating2.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        spnRating2.setModel(new javax.swing.SpinnerNumberModel(1, 1, 5, 1));

        spnRating3.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        spnRating3.setModel(new javax.swing.SpinnerNumberModel(1, 1, 5, 1));

        spnRating1.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        spnRating1.setModel(new javax.swing.SpinnerNumberModel(1, 1, 5, 1));

        spnRating4.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        spnRating4.setModel(new javax.swing.SpinnerNumberModel(1, 1, 5, 1));

        spnRating5.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        spnRating5.setModel(new javax.swing.SpinnerNumberModel(1, 1, 5, 1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Similar Users :");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Movies :");

        spnX2.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        spnX2.setModel(new javax.swing.SpinnerNumberModel(1, 1, 5, 1));

        spnK2.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        spnK2.setModel(new javax.swing.SpinnerNumberModel(1, 1, 5, 1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Movies");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Ratings");

        btnPreviousPage.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnPreviousPage.setText("Previous Page");
        btnPreviousPage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPreviousPageActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29)
                                .addComponent(spnK2))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                                .addComponent(spnX2, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(btnMovieRecommend, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48)
                        .addComponent(btnPreviousPage, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(cmbMovie2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cmbMovie3, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cmbMovie4, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cmbMovie5, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cmbMovie1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(76, 76, 76)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(spnRating2)
                                    .addComponent(spnRating1, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(spnRating5)
                                    .addComponent(spnRating4, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(spnRating3, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(16, 16, 16))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmbMovie1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(spnRating1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmbMovie2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(spnRating2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmbMovie3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(spnRating3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmbMovie4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(spnRating4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmbMovie5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(spnRating5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(spnX2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(spnK2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnPreviousPage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnMovieRecommend, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE))
                        .addGap(49, 49, 49))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void addMovieRating(HashMap<Integer, Integer> selectedRatings, HashSet<String> selectedMovieNames, JComboBox<String> combo, JSpinner spinner) {
        String movieName = combo.getSelectedItem().toString();

        if (selectedMovieNames.contains(movieName)) {
            throw new IllegalArgumentException("You cannot select the same movie more than once.");
        }

        selectedMovieNames.add(movieName);

        int movieId = system.getMovieIdByName(movieName);
        int rating = (int) spinner.getValue();

        if (rating < 1 || rating > 5) {
            throw new IllegalArgumentException("Ratings must be between 1 and 5");
        }

        selectedRatings.put(movieId, rating);
    }
    private void btnMovieRecommendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMovieRecommendActionPerformed
        // TODO add your handling code here:
        try {
            int x = (int) spnX2.getValue();
            int k = (int) spnK2.getValue();

            HashMap<Integer, Integer> selectedRatings = new HashMap<>();
            HashSet<String> selectedMovieNames = new HashSet<>();

            addMovieRating(selectedRatings, selectedMovieNames, cmbMovie1, spnRating1);
            addMovieRating(selectedRatings, selectedMovieNames, cmbMovie2, spnRating2);
            addMovieRating(selectedRatings, selectedMovieNames, cmbMovie3, spnRating3);
            addMovieRating(selectedRatings, selectedMovieNames, cmbMovie4, spnRating4);
            addMovieRating(selectedRatings, selectedMovieNames, cmbMovie5, spnRating5);

            ArrayList<String> recs = system.recommendFromManualRatings(selectedRatings, x, k);

            txtAreaMovieResult.setText("");
            for (String movie : recs) {
                txtAreaMovieResult.append(movie + "\n");
            }

        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
        }
    }//GEN-LAST:event_btnMovieRecommendActionPerformed

    private void btnPreviousPageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPreviousPageActionPerformed
        // TODO add your handling code here:
        if (previousPage != null) {
            previousPage.setVisible(true);
            this.setVisible(false);
        } else {
            GUI page1 = new GUI();
            page1.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_btnPreviousPageActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMovieRecommend;
    private javax.swing.JButton btnPreviousPage;
    private javax.swing.JComboBox<String> cmbMovie1;
    private javax.swing.JComboBox<String> cmbMovie2;
    private javax.swing.JComboBox<String> cmbMovie3;
    private javax.swing.JComboBox<String> cmbMovie4;
    private javax.swing.JComboBox<String> cmbMovie5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner spnK2;
    private javax.swing.JSpinner spnRating1;
    private javax.swing.JSpinner spnRating2;
    private javax.swing.JSpinner spnRating3;
    private javax.swing.JSpinner spnRating4;
    private javax.swing.JSpinner spnRating5;
    private javax.swing.JSpinner spnX2;
    private javax.swing.JTextArea txtAreaMovieResult;
    // End of variables declaration//GEN-END:variables
}
